# filtering

In [1]:
import cv2 
import matplotlib.pyplot as plt
import numpy as np

In [2]:
im1=cv2.imread("C:/Users/admin/Pictures/india.png")
print(im1)

[[[ 39 127 255]
  [ 39 127 255]
  [ 39 127 255]
  ...
  [ 39 127 254]
  [ 39 127 253]
  [ 40 127 254]]

 [[ 39 127 255]
  [ 39 127 255]
  [ 39 127 255]
  ...
  [ 39 127 253]
  [ 39 127 253]
  [ 40 127 254]]

 [[ 39 127 255]
  [ 39 127 255]
  [ 39 127 255]
  ...
  [ 39 126 252]
  [ 39 126 252]
  [ 39 126 253]]

 ...

 [[ 72 208  22]
  [ 73 208  23]
  [ 67 202  19]
  ...
  [ 68 206  15]
  [ 67 205  15]
  [ 69 209  14]]

 [[ 69 204  18]
  [ 65 200  14]
  [ 74 209  26]
  ...
  [ 68 207  16]
  [ 67 206  15]
  [ 69 209  14]]

 [[ 66 201  14]
  [ 68 204  18]
  [ 78 211  28]
  ...
  [ 69 208  17]
  [ 68 205  15]
  [ 69 209  14]]]


# filter2d

In [3]:
kernal=np.ones((5,5),np.float32)/25
filter=cv2.filter2D(im1,-1,kernal)

# blur

In [4]:
blur= cv2.blur(im1,(3,3))

# Gaussian blur

In [5]:
Gblur=cv2.GaussianBlur(im1,(7,7),0)

# bilateral filter

In [7]:
print(im1.shape)

(264, 296, 3)


In [8]:
Bfilter=cv2.bilateralFilter(im1,9,50,50)

# median filter

In [9]:
medianfilter= cv2.medianBlur(im1,5)

# Laplacian Filter

In [14]:
im2=cv2.imread("C:/Users/admin/Pictures/india.png",0)

In [15]:
lap = cv2.Laplacian(im2,cv2.CV_64F,ksize=3)