# filtering

In [1]:
import cv2 
import matplotlib.pyplot as plt
import numpy as np

In [2]:
im1=cv2.imread("india.png")
print(im1)

[[[ 39 127 255]
  [ 39 127 255]
  [ 39 127 255]
  ...
  [ 39 127 254]
  [ 39 127 253]
  [ 40 127 254]]

 [[ 39 127 255]
  [ 39 127 255]
  [ 39 127 255]
  ...
  [ 39 127 253]
  [ 39 127 253]
  [ 40 127 254]]

 [[ 39 127 255]
  [ 39 127 255]
  [ 39 127 255]
  ...
  [ 39 126 252]
  [ 39 126 252]
  [ 39 126 253]]

 ...

 [[ 72 208  22]
  [ 73 208  23]
  [ 67 202  19]
  ...
  [ 68 206  15]
  [ 67 205  15]
  [ 69 209  14]]

 [[ 69 204  18]
  [ 65 200  14]
  [ 74 209  26]
  ...
  [ 68 207  16]
  [ 67 206  15]
  [ 69 209  14]]

 [[ 66 201  14]
  [ 68 204  18]
  [ 78 211  28]
  ...
  [ 69 208  17]
  [ 68 205  15]
  [ 69 209  14]]]


# filter2d

In [3]:
kernal=np.ones((5,5),np.float32)/25
filter=cv2.filter2D(im1,-1,kernal)

# blur

In [4]:
blur= cv2.blur(im1,(3,3))

# Gaussian blur

In [5]:
Gblur=cv2.GaussianBlur(im1,(7,7),0)

# bilateral filter

In [6]:
print(im1.shape)

(264, 296, 3)


In [7]:
Bfilter=cv2.bilateralFilter(im1,9,50,50)

# median filter

In [8]:
medianfilter= cv2.medianBlur(im1,5)

# Laplacian Filter

In [9]:
im2=cv2.imread("india.png",0)

In [10]:
lap = cv2.Laplacian(im2,cv2.CV_64F,ksize=3)

In [11]:
lap = np.uint8(np.absolute(lap))

# Sobel Filter

In [12]:
im3=cv2.imread("sudoku.jfif",0)
print(im3)

[[255 240 253 ... 255 244 249]
 [240 255 255 ... 250 255 249]
 [253 253 116 ...  29  97 154]
 ...
 [249 253 121 ...  13  86 139]
 [252 255 236 ... 222 247 252]
 [255 250 250 ... 255 255 249]]


In [13]:
sobelx = cv2.Sobel(im3,cv2.CV_64F,1,0,ksize=3)
sobelx = np.uint8(np.absolute(sobelx))
print(sobelx)

[[  0  26   0 ...  20  14   0]
 [  0 109 225 ...  45 117   0]
 [  0 157  52 ...  57 203   0]
 ...
 [  0 182  92 ...  63 225   0]
 [  0 165  29 ...  78 180   0]
 [  0  42  40 ...  24  48   0]]


In [ ]:
cv2.imshow('image',im3)
cv2.imshow('Sobel',sobelx)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
sobely = cv2.Sobel(im3,cv2.CV_64F,0,1,ksize=3)
sobely = np.uint8(np.absolute(sobely))
print(sobely)

[[  0   0   0 ...   0   0   0]
 [ 22 113 217 ...  43 103 228]
 [ 12 157 184 ... 145 101 146]
 ...
 [  2 152 120 ...   9  35 122]
 [  6 129 241 ... 108 178  46]
 [  0   0   0 ...   0   0   0]]


In [15]:
cv2.imshow('image',im3)
cv2.imshow('Sobelx',sobelx)
cv2.imshow('Sobely',sobely)
cv2.waitKey(0)
cv2.destroyAllWindows()