In [1]:
import cv2 as cv
import numpy as np

 # read image

In [2]:
img=cv.imread("hh.jfif")

# color conversation

In [3]:
imgrgb = cv.cvtColor(img,cv.COLOR_BGR2RGB)

# resize image 

In [4]:
vec = imgrgb.reshape((-1,3))

In [5]:
vec 

array([[245,  65,  30],
       [239,  59,  24],
       [234,  50,  16],
       ...,
       [ 94, 146,  10],
       [ 92, 143,  12],
       [ 99, 150,  19]], dtype=uint8)

# Unit Conversion 8 to 32

In [6]:
vecy = np.float32(vec)

In [7]:
vecy

array([[245.,  65.,  30.],
       [239.,  59.,  24.],
       [234.,  50.,  16.],
       ...,
       [ 94., 146.,  10.],
       [ 92., 143.,  12.],
       [ 99., 150.,  19.]], dtype=float32)

# Iteration Termination Criteria

In [8]:
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 100, 1)

# CLUSTER CONDITIONS

In [9]:
k = 3
attempts = 100

# K-Means Clustering

In [10]:
compactness,label,center = cv.kmeans(vecy,k,None,criteria,attempts,cv.KMEANS_PP_CENTERS)

In [12]:
center

array([[190.32295 ,  50.44948 ,  37.94664 ],
       [177.71924 , 161.60384 ,  52.783276],
       [226.17155 , 180.40056 , 128.69289 ]], dtype=float32)

# Unit Conversion 32 to 8

In [13]:
centery = np.uint8(center)

In [14]:
centery

array([[190,  50,  37],
       [177, 161,  52],
       [226, 180, 128]], dtype=uint8)

# Flattening and Reshape

In [15]:
res = centery[label.flatten()]
res_img = res.reshape((imgrgb.shape)) 

In [16]:
res_img

array([[[190,  50,  37],
        [190,  50,  37],
        [190,  50,  37],
        ...,
        [226, 180, 128],
        [226, 180, 128],
        [226, 180, 128]],

       [[190,  50,  37],
        [190,  50,  37],
        [190,  50,  37],
        ...,
        [226, 180, 128],
        [226, 180, 128],
        [226, 180, 128]],

       [[190,  50,  37],
        [190,  50,  37],
        [190,  50,  37],
        ...,
        [226, 180, 128],
        [226, 180, 128],
        [226, 180, 128]],

       ...,

       [[177, 161,  52],
        [177, 161,  52],
        [177, 161,  52],
        ...,
        [177, 161,  52],
        [177, 161,  52],
        [177, 161,  52]],

       [[177, 161,  52],
        [177, 161,  52],
        [177, 161,  52],
        ...,
        [177, 161,  52],
        [177, 161,  52],
        [177, 161,  52]],

       [[177, 161,  52],
        [177, 161,  52],
        [177, 161,  52],
        ...,
        [177, 161,  52],
        [177, 161,  52],
        [177, 161,  52]]

# Display the Original and Segmented image

In [19]:
cv.imshow('Original',img)
cv.imshow('Segmented',res_img)
cv.waitKey(0)
cv.destroyAllWindows()

# Image Mean Shift Segmentation

In [24]:
# Apply mean shift segmentation
segmented_image = cv.pyrMeanShiftFiltering(img,40,40)

# Display the segmentated image
cv.imshow('Original',img)
cv.imshow('Segmented_image',segmented_image)
cv.waitKey(0)
cv.destroyAllWindows()