# Heading Rotation and Translation

In [1]:
import cv2
import numpy as np

In [2]:
im1=cv2.imread("img1.jfif")
im2=cv2.imread("img2.jfif")

In [3]:
im1

array([[[237, 177, 111],
        [237, 177, 111],
        [237, 177, 111],
        ...,
        [237, 177, 111],
        [237, 177, 111],
        [237, 177, 111]],

       [[235, 175, 109],
        [235, 175, 109],
        [235, 175, 109],
        ...,
        [235, 175, 109],
        [235, 175, 109],
        [235, 175, 109]],

       [[233, 174, 105],
        [233, 174, 105],
        [233, 174, 105],
        ...,
        [233, 174, 105],
        [233, 174, 105],
        [233, 174, 105]],

       ...,

       [[ 27,  77,  29],
        [ 28,  75,  29],
        [ 34,  77,  34],
        ...,
        [ 90, 146,  57],
        [ 96, 157,  66],
        [ 83, 147,  52]],

       [[  3,  53,   5],
        [  0,  45,   0],
        [  2,  45,   2],
        ...,
        [ 35,  93,   5],
        [ 52, 114,  24],
        [ 43, 108,  16]],

       [[  0,  47,   0],
        [  0,  36,   0],
        [  0,  33,   0],
        ...,
        [ 32,  92,   4],
        [ 36,  98,   8],
        [ 46, 111,  19]]

In [4]:
im2

array([[[253, 247, 242],
        [250, 244, 239],
        [251, 245, 240],
        ...,
        [254, 253, 249],
        [254, 253, 249],
        [254, 253, 249]],

       [[249, 243, 238],
        [246, 240, 235],
        [247, 241, 236],
        ...,
        [254, 253, 249],
        [254, 253, 249],
        [254, 253, 249]],

       [[248, 242, 237],
        [244, 238, 233],
        [244, 238, 233],
        ...,
        [254, 253, 249],
        [254, 253, 249],
        [254, 253, 249]],

       ...,

       [[244, 235, 222],
        [246, 238, 225],
        [234, 225, 216],
        ...,
        [224, 218, 211],
        [224, 218, 211],
        [224, 218, 211]],

       [[245, 236, 223],
        [248, 240, 227],
        [236, 227, 218],
        ...,
        [227, 221, 214],
        [227, 221, 214],
        [227, 221, 214]],

       [[247, 238, 225],
        [250, 242, 229],
        [238, 229, 220],
        ...,
        [230, 224, 217],
        [230, 224, 217],
        [230, 224, 217]]

In [5]:
im1_shape=im1.shape
im2_shape=im2.shape

In [6]:
im1_resized=cv2.resize(im1,(230,290))
im2_resized=cv2.resize(im2,(230,290))

In [7]:
shp = im1.shape
print(shp)

(180, 216, 3)


In [8]:
height,width = im1.shape[:2]
print(height)
print(width)

180
216


In [9]:
cent=(height/2,width/2)
cent

(90.0, 108.0)

In [10]:
rotation_matrix=cv2.getRotationMatrix2D(center=cent,angle=25,scale=0.5)

In [11]:
print(rotation_matrix)

[[ 0.45315389  0.21130913 26.39476345]
 [-0.21130913  0.45315389 78.07720128]]


In [12]:
rotated_im=cv2.warpAffine(src=im1,M=rotation_matrix,dsize=(width,height))

In [ ]:
cv2.imshow("Original_Image",im1)
cv2.imshow("Rotated_Image",rotated_im)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Translation Matrix

In [13]:
tx,ty=width/2,height/2
print(tx)
print(ty)

In [14]:
Translation_matrix=np.array([[1,0,tx],[0,1,ty]])

In [15]:
Translation_matrix

array([[  1.,   0., 108.],
       [  0.,   1.,  90.]])

In [16]:
Trans_im=cv2.warpAffine(src=im1,M=Translation_matrix,dsize=(width,height))

In [ ]:
cv2.imshow("Original_Image",im1)
cv2.imshow("Rotated_Image",Trans_im)
cv2.waitKey(0)
cv2.destroyAllWindows()